import type { TextOverlay } from '$lib/types/index.js';
import { DEFAULT_TEXT_SHADOW, DEFAULT_TEXT_OUTLINE } from '$lib/types/index.js';

export type TitleCategory = 'basic' | 'lower-third' | 'animated' | 'social' | 'cinematic' | 'neon';

export interface TitleTemplate {
	id: string;
	name: string;
	category: TitleCategory;
	preview: string;
	overlays: Partial<TextOverlay>[];
	duration: number;
}

const shadow = () => ({ ...DEFAULT_TEXT_SHADOW });
const outline = () => ({ ...DEFAULT_TEXT_OUTLINE });

export const TITLE_TEMPLATES: TitleTemplate[] = [
	// ── Basic Titles ────────────────────────────────────────────────
	{
		id: 'centered-bold',
		name: 'Centered Bold',
		category: 'basic',
		preview: 'Large centered white text, bold weight',
		duration: 5,
		overlays: [
			{
				text: 'Your Title',
				x: 0.5,
				y: 0.5,
				fontSize: 72,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'none',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'left-aligned',
		name: 'Left Aligned',
		category: 'basic',
		preview: 'Medium left-aligned text',
		duration: 5,
		overlays: [
			{
				text: 'Your Title',
				x: 0.1,
				y: 0.5,
				fontSize: 48,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'left',
				opacity: 1,
				animation: 'none',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'right-aligned',
		name: 'Right Aligned',
		category: 'basic',
		preview: 'Medium right-aligned text',
		duration: 5,
		overlays: [
			{
				text: 'Your Title',
				x: 0.9,
				y: 0.5,
				fontSize: 48,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'right',
				opacity: 1,
				animation: 'none',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'subtitle',
		name: 'Subtitle',
		category: 'basic',
		preview: 'Small centered text at bottom',
		duration: 5,
		overlays: [
			{
				text: 'Subtitle text here',
				x: 0.5,
				y: 0.85,
				fontSize: 28,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#cccccc',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'none',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'chapter-title',
		name: 'Chapter Title',
		category: 'basic',
		preview: 'Large title with smaller subtitle below',
		duration: 5,
		overlays: [
			{
				text: 'Chapter One',
				x: 0.5,
				y: 0.42,
				fontSize: 64,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'none',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: 'The Beginning',
				x: 0.5,
				y: 0.55,
				fontSize: 28,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#aaaaaa',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'none',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},

	// ── Lower Thirds ────────────────────────────────────────────────
	{
		id: 'lower-third-bar',
		name: 'Bar Lower Third',
		category: 'lower-third',
		preview: 'Name on colored bar with subtitle',
		duration: 6,
		overlays: [
			{
				text: 'John Smith',
				x: 0.15,
				y: 0.82,
				fontSize: 32,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: '#2563eb',
				alignment: 'left',
				opacity: 1,
				animation: 'slideLeft',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: 'Creative Director',
				x: 0.15,
				y: 0.89,
				fontSize: 20,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: '#1e40af',
				alignment: 'left',
				opacity: 1,
				animation: 'slideLeft',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'lower-third-minimal',
		name: 'Minimal Lower Third',
		category: 'lower-third',
		preview: 'Name with thin underline accent',
		duration: 6,
		overlays: [
			{
				text: 'Jane Doe',
				x: 0.1,
				y: 0.84,
				fontSize: 30,
				fontWeight: 600,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'left',
				opacity: 1,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: { enabled: true, color: '#ffffff', width: 1 },
			},
			{
				text: 'Producer',
				x: 0.1,
				y: 0.9,
				fontSize: 18,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#cccccc',
				backgroundColor: 'transparent',
				alignment: 'left',
				opacity: 0.8,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'lower-third-gradient',
		name: 'Gradient Lower Third',
		category: 'lower-third',
		preview: 'Name on dark gradient bar',
		duration: 6,
		overlays: [
			{
				text: 'Alex Johnson',
				x: 0.15,
				y: 0.83,
				fontSize: 30,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'rgba(0, 0, 0, 0.7)',
				alignment: 'left',
				opacity: 1,
				animation: 'slideLeft',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: 'CEO & Founder',
				x: 0.15,
				y: 0.9,
				fontSize: 18,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#e5e5e5',
				backgroundColor: 'rgba(0, 0, 0, 0.5)',
				alignment: 'left',
				opacity: 1,
				animation: 'slideLeft',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'lower-third-boxed',
		name: 'Boxed Lower Third',
		category: 'lower-third',
		preview: 'Name in bordered box',
		duration: 6,
		overlays: [
			{
				text: 'Sam Williams',
				x: 0.12,
				y: 0.84,
				fontSize: 28,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'rgba(37, 99, 235, 0.9)',
				alignment: 'left',
				opacity: 1,
				animation: 'scaleIn',
				shadow: shadow(),
				outline: { enabled: true, color: '#93c5fd', width: 2 },
			},
			{
				text: 'Marketing Lead',
				x: 0.12,
				y: 0.91,
				fontSize: 18,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'rgba(30, 64, 175, 0.9)',
				alignment: 'left',
				opacity: 1,
				animation: 'scaleIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'lower-third-split',
		name: 'Split Lower Third',
		category: 'lower-third',
		preview: 'Two-tone split bar with name and title',
		duration: 6,
		overlays: [
			{
				text: 'Morgan Lee',
				x: 0.12,
				y: 0.84,
				fontSize: 28,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: '#dc2626',
				alignment: 'left',
				opacity: 1,
				animation: 'slideLeft',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: 'Head of Design',
				x: 0.12,
				y: 0.91,
				fontSize: 18,
				fontWeight: 500,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: '#1f2937',
				alignment: 'left',
				opacity: 1,
				animation: 'slideLeft',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},

	// ── Animated ────────────────────────────────────────────────────
	{
		id: 'fade-in-up',
		name: 'Fade In Up',
		category: 'animated',
		preview: 'Fades in while sliding upward',
		duration: 5,
		overlays: [
			{
				text: 'Fade In Title',
				x: 0.5,
				y: 0.5,
				fontSize: 56,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'slideUp',
				shadow: { enabled: true, color: 'rgba(0,0,0,0.5)', offsetX: 0, offsetY: 4, blur: 8 },
				outline: outline(),
			},
		],
	},
	{
		id: 'typewriter',
		name: 'Typewriter',
		category: 'animated',
		preview: 'Types out letter by letter',
		duration: 5,
		overlays: [
			{
				text: 'Typing this out...',
				x: 0.5,
				y: 0.5,
				fontSize: 42,
				fontWeight: 400,
				fontFamily: 'Courier New',
				color: '#00ff88',
				backgroundColor: 'rgba(0, 0, 0, 0.8)',
				alignment: 'center',
				opacity: 1,
				animation: 'typewriter',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'slide-from-left',
		name: 'Slide From Left',
		category: 'animated',
		preview: 'Slides in from the left side',
		duration: 5,
		overlays: [
			{
				text: 'Slide In',
				x: 0.5,
				y: 0.5,
				fontSize: 56,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'slideLeft',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'scale-pop',
		name: 'Scale Pop',
		category: 'animated',
		preview: 'Scales up from small to full size',
		duration: 5,
		overlays: [
			{
				text: 'POP!',
				x: 0.5,
				y: 0.5,
				fontSize: 80,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#facc15',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'scaleIn',
				shadow: { enabled: true, color: 'rgba(0,0,0,0.6)', offsetX: 0, offsetY: 3, blur: 10 },
				outline: { enabled: true, color: '#000000', width: 3 },
			},
		],
	},
	{
		id: 'blur-reveal',
		name: 'Blur Reveal',
		category: 'animated',
		preview: 'Fades in from blurred to sharp',
		duration: 5,
		overlays: [
			{
				text: 'Revealed',
				x: 0.5,
				y: 0.5,
				fontSize: 60,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: { enabled: true, color: 'rgba(255,255,255,0.3)', offsetX: 0, offsetY: 0, blur: 15 },
				outline: outline(),
			},
		],
	},

	// ── Social Media ────────────────────────────────────────────────
	{
		id: 'youtube-subscribe',
		name: 'Subscribe CTA',
		category: 'social',
		preview: 'YouTube-style subscribe call-to-action',
		duration: 5,
		overlays: [
			{
				text: 'SUBSCRIBE',
				x: 0.5,
				y: 0.82,
				fontSize: 36,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: '#ff0000',
				alignment: 'center',
				opacity: 1,
				animation: 'scaleIn',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: 'Hit the bell for notifications',
				x: 0.5,
				y: 0.9,
				fontSize: 18,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 0.9,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'like-share',
		name: 'Like & Share',
		category: 'social',
		preview: 'Like and share reminder',
		duration: 4,
		overlays: [
			{
				text: 'LIKE & SHARE',
				x: 0.5,
				y: 0.5,
				fontSize: 52,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'rgba(37, 99, 235, 0.9)',
				alignment: 'center',
				opacity: 1,
				animation: 'scaleIn',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: 'If you enjoyed this video!',
				x: 0.5,
				y: 0.6,
				fontSize: 24,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#e5e5e5',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'slideUp',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'follow-me',
		name: 'Follow Me',
		category: 'social',
		preview: 'Social handle display',
		duration: 5,
		overlays: [
			{
				text: '@yourhandle',
				x: 0.5,
				y: 0.5,
				fontSize: 48,
				fontWeight: 700,
				fontFamily: 'Inter',
				color: '#e879f9',
				backgroundColor: 'rgba(0, 0, 0, 0.7)',
				alignment: 'center',
				opacity: 1,
				animation: 'slideUp',
				shadow: { enabled: true, color: 'rgba(232, 121, 249, 0.4)', offsetX: 0, offsetY: 0, blur: 12 },
				outline: outline(),
			},
			{
				text: 'Follow for more content',
				x: 0.5,
				y: 0.6,
				fontSize: 22,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 0.8,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'countdown',
		name: 'Countdown',
		category: 'social',
		preview: 'Large countdown number display',
		duration: 3,
		overlays: [
			{
				text: '3',
				x: 0.5,
				y: 0.45,
				fontSize: 120,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'scaleIn',
				shadow: { enabled: true, color: 'rgba(0,0,0,0.5)', offsetX: 0, offsetY: 4, blur: 12 },
				outline: { enabled: true, color: '#ef4444', width: 4 },
			},
		],
	},
	{
		id: 'end-screen',
		name: 'End Screen',
		category: 'social',
		preview: 'End card with thanks message and CTA',
		duration: 8,
		overlays: [
			{
				text: 'Thanks for Watching!',
				x: 0.5,
				y: 0.35,
				fontSize: 56,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'slideUp',
				shadow: { enabled: true, color: 'rgba(0,0,0,0.5)', offsetX: 0, offsetY: 3, blur: 8 },
				outline: outline(),
			},
			{
				text: 'Subscribe for more videos',
				x: 0.5,
				y: 0.5,
				fontSize: 28,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#d4d4d4',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: '@yourhandle',
				x: 0.5,
				y: 0.62,
				fontSize: 24,
				fontWeight: 600,
				fontFamily: 'Inter',
				color: '#60a5fa',
				backgroundColor: 'rgba(0, 0, 0, 0.6)',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	// ── Cinematic ──────────────────────────────────────────────────
	{
		id: 'cinematic-intro',
		name: 'Cinematic Intro',
		category: 'cinematic',
		preview: 'Epic title with letterbox bars feel',
		duration: 6,
		overlays: [
			{
				text: 'THE BEGINNING',
				x: 0.5,
				y: 0.45,
				fontSize: 48,
				fontWeight: 900,
				fontFamily: 'Georgia',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: { enabled: true, color: 'rgba(0,0,0,0.8)', offsetX: 0, offsetY: 2, blur: 12 },
				outline: outline(),
			},
			{
				text: 'A Story Worth Telling',
				x: 0.5,
				y: 0.55,
				fontSize: 20,
				fontWeight: 400,
				fontFamily: 'Georgia',
				color: '#cccccc',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 0.8,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'cinematic-quote',
		name: 'Cinematic Quote',
		category: 'cinematic',
		preview: 'Centered italic quote with attribution',
		duration: 7,
		overlays: [
			{
				text: '"The only way to do great work is to love what you do."',
				x: 0.5,
				y: 0.45,
				fontSize: 36,
				fontWeight: 400,
				fontFamily: 'Georgia',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: { enabled: true, color: 'rgba(0,0,0,0.6)', offsetX: 0, offsetY: 2, blur: 8 },
				outline: outline(),
			},
			{
				text: '- Steve Jobs',
				x: 0.5,
				y: 0.58,
				fontSize: 20,
				fontWeight: 600,
				fontFamily: 'Georgia',
				color: '#aaaaaa',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 0.8,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},
	{
		id: 'cinematic-location',
		name: 'Location Card',
		category: 'cinematic',
		preview: 'Location name with subtle underline',
		duration: 5,
		overlays: [
			{
				text: 'NEW YORK CITY',
				x: 0.5,
				y: 0.88,
				fontSize: 24,
				fontWeight: 600,
				fontFamily: 'Inter',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: { enabled: true, color: 'rgba(255,255,255,0.3)', width: 1 },
			},
		],
	},
	{
		id: 'cinematic-credits',
		name: 'Directed By',
		category: 'cinematic',
		preview: 'Film credits style',
		duration: 5,
		overlays: [
			{
				text: 'DIRECTED BY',
				x: 0.5,
				y: 0.42,
				fontSize: 16,
				fontWeight: 400,
				fontFamily: 'Inter',
				color: '#999999',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
			{
				text: 'YOUR NAME',
				x: 0.5,
				y: 0.52,
				fontSize: 44,
				fontWeight: 700,
				fontFamily: 'Georgia',
				color: '#ffffff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: shadow(),
				outline: outline(),
			},
		],
	},

	// ── Neon ────────────────────────────────────────────────────────
	{
		id: 'neon-glow',
		name: 'Neon Glow',
		category: 'neon',
		preview: 'Bright neon glowing text',
		duration: 5,
		overlays: [
			{
				text: 'NEON',
				x: 0.5,
				y: 0.5,
				fontSize: 80,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ff00ff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: { enabled: true, color: '#ff00ff', offsetX: 0, offsetY: 0, blur: 20 },
				outline: { enabled: true, color: '#ff66ff', width: 2 },
			},
		],
	},
	{
		id: 'neon-blue',
		name: 'Blue Neon',
		category: 'neon',
		preview: 'Blue neon sign effect',
		duration: 5,
		overlays: [
			{
				text: 'ELECTRIC',
				x: 0.5,
				y: 0.5,
				fontSize: 72,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#00aaff',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'scaleIn',
				shadow: { enabled: true, color: '#0088ff', offsetX: 0, offsetY: 0, blur: 25 },
				outline: { enabled: true, color: '#66ccff', width: 2 },
			},
		],
	},
	{
		id: 'neon-retro',
		name: 'Retro Neon',
		category: 'neon',
		preview: 'Retro 80s neon style',
		duration: 6,
		overlays: [
			{
				text: 'RETRO',
				x: 0.5,
				y: 0.42,
				fontSize: 72,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#ff4488',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'scaleIn',
				shadow: { enabled: true, color: '#ff4488', offsetX: 0, offsetY: 0, blur: 18 },
				outline: { enabled: true, color: '#ff88aa', width: 2 },
			},
			{
				text: 'VIBES',
				x: 0.5,
				y: 0.58,
				fontSize: 72,
				fontWeight: 900,
				fontFamily: 'Inter',
				color: '#44ffdd',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'scaleIn',
				shadow: { enabled: true, color: '#44ffdd', offsetX: 0, offsetY: 0, blur: 18 },
				outline: { enabled: true, color: '#88ffee', width: 2 },
			},
		],
	},
	{
		id: 'neon-sign',
		name: 'Neon Sign',
		category: 'neon',
		preview: 'Bar sign style neon text',
		duration: 5,
		overlays: [
			{
				text: 'OPEN',
				x: 0.5,
				y: 0.5,
				fontSize: 96,
				fontWeight: 900,
				fontFamily: 'Courier New',
				color: '#ff3333',
				backgroundColor: 'transparent',
				alignment: 'center',
				opacity: 1,
				animation: 'fadeIn',
				shadow: { enabled: true, color: '#ff0000', offsetX: 0, offsetY: 0, blur: 30 },
				outline: { enabled: true, color: '#ff6666', width: 3 },
			},
		],
	},
];

export const TITLE_CATEGORIES: { label: string; value: TitleCategory | 'all' }[] = [
	{ label: 'All', value: 'all' },
	{ label: 'Basic', value: 'basic' },
	{ label: 'Lower Thirds', value: 'lower-third' },
	{ label: 'Animated', value: 'animated' },
	{ label: 'Social', value: 'social' },
	{ label: 'Cinematic', value: 'cinematic' },
	{ label: 'Neon', value: 'neon' },
];

export function getTemplatesByCategory(category: TitleCategory | 'all'): TitleTemplate[] {
	if (category === 'all') return TITLE_TEMPLATES;
	return TITLE_TEMPLATES.filter((t) => t.category === category);
}

export function getTemplateById(id: string): TitleTemplate | undefined {
	return TITLE_TEMPLATES.find((t) => t.id === id);
}

/** Category display colors for preview cards */
export const CATEGORY_COLORS: Record<TitleCategory, { bg: string; accent: string }> = {
	basic: { bg: '#1e293b', accent: '#64748b' },
	'lower-third': { bg: '#172554', accent: '#2563eb' },
	animated: { bg: '#1a1a2e', accent: '#a855f7' },
	social: { bg: '#1c1917', accent: '#ef4444' },
	cinematic: { bg: '#1a1a1a', accent: '#d4a040' },
	neon: { bg: '#0a0a1a', accent: '#ff00ff' },
};
