// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO video_comments (video_id, user_id, author_name, author_avatar, body, timestamp_seconds)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, video_id, user_id, author_name, author_avatar, body, timestamp_seconds, created_at, updated_at
`

type CreateCommentParams struct {
	VideoID          pgtype.UUID `json:"video_id"`
	UserID           pgtype.UUID `json:"user_id"`
	AuthorName       string      `json:"author_name"`
	AuthorAvatar     pgtype.Text `json:"author_avatar"`
	Body             string      `json:"body"`
	TimestampSeconds pgtype.Int4 `json:"timestamp_seconds"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (VideoComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.VideoID,
		arg.UserID,
		arg.AuthorName,
		arg.AuthorAvatar,
		arg.Body,
		arg.TimestampSeconds,
	)
	var i VideoComment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.Body,
		&i.TimestampSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentsByVideo = `-- name: GetCommentsByVideo :many
SELECT id, video_id, user_id, author_name, author_avatar, body, timestamp_seconds, created_at, updated_at FROM video_comments
WHERE video_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCommentsByVideo(ctx context.Context, videoID pgtype.UUID) ([]VideoComment, error) {
	rows, err := q.db.Query(ctx, getCommentsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoComment{}
	for rows.Next() {
		var i VideoComment
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.UserID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.Body,
			&i.TimestampSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM video_comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}
