// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusRunning   JobStatus = "running"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type JobType string

const (
	JobTypeTranscode  JobType = "transcode"
	JobTypeThumbnail  JobType = "thumbnail"
	JobTypeTranscribe JobType = "transcribe"
)

func (e *JobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobType(s)
	case string:
		*e = JobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobType: %T", src)
	}
	return nil
}

type NullJobType struct {
	JobType JobType `json:"job_type"`
	Valid   bool    `json:"valid"` // Valid is true if JobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobType), nil
}

type ShareMode string

const (
	ShareModePublic   ShareMode = "public"
	ShareModeUnlisted ShareMode = "unlisted"
	ShareModePrivate  ShareMode = "private"
)

func (e *ShareMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShareMode(s)
	case string:
		*e = ShareMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ShareMode: %T", src)
	}
	return nil
}

type NullShareMode struct {
	ShareMode ShareMode `json:"share_mode"`
	Valid     bool      `json:"valid"` // Valid is true if ShareMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShareMode) Scan(value interface{}) error {
	if value == nil {
		ns.ShareMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShareMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShareMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShareMode), nil
}

type VideoStatus string

const (
	VideoStatusUploading  VideoStatus = "uploading"
	VideoStatusProcessing VideoStatus = "processing"
	VideoStatusReady      VideoStatus = "ready"
	VideoStatusFailed     VideoStatus = "failed"
)

func (e *VideoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoStatus(s)
	case string:
		*e = VideoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoStatus: %T", src)
	}
	return nil
}

type NullVideoStatus struct {
	VideoStatus VideoStatus `json:"video_status"`
	Valid       bool        `json:"valid"` // Valid is true if VideoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VideoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoStatus), nil
}

type ProcessingJob struct {
	ID          pgtype.UUID        `json:"id"`
	VideoID     pgtype.UUID        `json:"video_id"`
	Type        JobType            `json:"type"`
	Status      JobStatus          `json:"status"`
	Progress    int32              `json:"progress"`
	Error       pgtype.Text        `json:"error"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	AuthProvider   string             `json:"auth_provider"`
	AuthProviderID pgtype.Text        `json:"auth_provider_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Video struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Status          VideoStatus        `json:"status"`
	DurationMs      pgtype.Int4        `json:"duration_ms"`
	RecordingSource pgtype.Text        `json:"recording_source"`
	SourceKey       pgtype.Text        `json:"source_key"`
	HlsKey          pgtype.Text        `json:"hls_key"`
	ThumbnailKey    pgtype.Text        `json:"thumbnail_key"`
	GifKey          pgtype.Text        `json:"gif_key"`
	ShareMode       ShareMode          `json:"share_mode"`
	UploadID        pgtype.Text        `json:"upload_id"`
	UploadParts     []byte             `json:"upload_parts"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
