// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processing_jobs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcessingJob = `-- name: CreateProcessingJob :one
INSERT INTO processing_jobs (video_id, type)
VALUES ($1, $2)
RETURNING id, video_id, type, status, progress, error, started_at, completed_at, created_at
`

type CreateProcessingJobParams struct {
	VideoID pgtype.UUID `json:"video_id"`
	Type    JobType     `json:"type"`
}

func (q *Queries) CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, createProcessingJob, arg.VideoID, arg.Type)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProcessingJobsByVideo = `-- name: GetProcessingJobsByVideo :many
SELECT id, video_id, type, status, progress, error, started_at, completed_at, created_at FROM processing_jobs
WHERE video_id = $1
ORDER BY created_at
`

func (q *Queries) GetProcessingJobsByVideo(ctx context.Context, videoID pgtype.UUID) ([]ProcessingJob, error) {
	rows, err := q.db.Query(ctx, getProcessingJobsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcessingJob{}
	for rows.Next() {
		var i ProcessingJob
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcessingJobStatus = `-- name: UpdateProcessingJobStatus :exec
UPDATE processing_jobs SET
    status = $2,
    progress = $3,
    error = $4,
    started_at = $5,
    completed_at = $6
WHERE id = $1
`

type UpdateProcessingJobStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      JobStatus          `json:"status"`
	Progress    int32              `json:"progress"`
	Error       pgtype.Text        `json:"error"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateProcessingJobStatus(ctx context.Context, arg UpdateProcessingJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateProcessingJobStatus,
		arg.ID,
		arg.Status,
		arg.Progress,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}
