// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :one
INSERT INTO video_reactions (video_id, emoji, reactor_name, reactor_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, video_id, emoji, reactor_name, reactor_user_id, created_at
`

type AddReactionParams struct {
	VideoID       pgtype.UUID `json:"video_id"`
	Emoji         string      `json:"emoji"`
	ReactorName   pgtype.Text `json:"reactor_name"`
	ReactorUserID pgtype.UUID `json:"reactor_user_id"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (VideoReaction, error) {
	row := q.db.QueryRow(ctx, addReaction, arg.VideoID, arg.Emoji, arg.ReactorName, arg.ReactorUserID)
	var i VideoReaction
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Emoji,
		&i.ReactorName,
		&i.ReactorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionsByVideo = `-- name: GetReactionsByVideo :many
SELECT id, video_id, emoji, reactor_name, reactor_user_id, created_at FROM video_reactions
WHERE video_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReactionsByVideo(ctx context.Context, videoID pgtype.UUID) ([]VideoReaction, error) {
	rows, err := q.db.Query(ctx, getReactionsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoReaction{}
	for rows.Next() {
		var i VideoReaction
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Emoji,
			&i.ReactorName,
			&i.ReactorUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReactionCounts = `-- name: GetReactionCounts :many
SELECT emoji, COUNT(*)::integer AS count
FROM video_reactions
WHERE video_id = $1
GROUP BY emoji
ORDER BY count DESC
`

type GetReactionCountsRow struct {
	Emoji string `json:"emoji"`
	Count int32  `json:"count"`
}

func (q *Queries) GetReactionCounts(ctx context.Context, videoID pgtype.UUID) ([]GetReactionCountsRow, error) {
	rows, err := q.db.Query(ctx, getReactionCounts, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReactionCountsRow{}
	for rows.Next() {
		var i GetReactionCountsRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
