// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_views.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordView = `-- name: RecordView :one
WITH inserted AS (
    INSERT INTO video_views (video_id, viewer_ip, viewer_user_id)
    VALUES ($1, $2, $3)
    RETURNING id, video_id, viewer_ip, viewer_user_id, watched_seconds, created_at
)
UPDATE videos SET view_count = COALESCE(view_count, 0) + 1
WHERE id = $1
RETURNING view_count
`

type RecordViewParams struct {
	VideoID      pgtype.UUID `json:"video_id"`
	ViewerIp     pgtype.Text `json:"viewer_ip"`
	ViewerUserID pgtype.UUID `json:"viewer_user_id"`
}

func (q *Queries) RecordView(ctx context.Context, arg RecordViewParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, recordView, arg.VideoID, arg.ViewerIp, arg.ViewerUserID)
	var view_count pgtype.Int4
	err := row.Scan(&view_count)
	return view_count, err
}

const getViewCount = `-- name: GetViewCount :one
SELECT COALESCE(view_count, 0)::integer AS view_count
FROM videos
WHERE id = $1
`

func (q *Queries) GetViewCount(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getViewCount, id)
	var view_count int32
	err := row.Scan(&view_count)
	return view_count, err
}

const hasRecentView = `-- name: HasRecentView :one
SELECT EXISTS(
    SELECT 1 FROM video_views
    WHERE video_id = $1 AND viewer_ip = $2
    AND created_at > NOW() - INTERVAL '1 hour'
) AS has_recent
`

type HasRecentViewParams struct {
	VideoID  pgtype.UUID `json:"video_id"`
	ViewerIp pgtype.Text `json:"viewer_ip"`
}

func (q *Queries) HasRecentView(ctx context.Context, arg HasRecentViewParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentView, arg.VideoID, arg.ViewerIp)
	var has_recent bool
	err := row.Scan(&has_recent)
	return has_recent, err
}
