// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVideosByUser = `-- name: CountVideosByUser :one
SELECT COUNT(*) FROM videos
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountVideosByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVideosByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (user_id, title, recording_source)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, description, status, duration_ms, recording_source, source_key, hls_key, thumbnail_key, gif_key, share_mode, upload_id, upload_parts, created_at, updated_at, deleted_at, view_count
`

type CreateVideoParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Title           string      `json:"title"`
	RecordingSource pgtype.Text `json:"recording_source"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.UserID, arg.Title, arg.RecordingSource)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DurationMs,
		&i.RecordingSource,
		&i.SourceKey,
		&i.HlsKey,
		&i.ThumbnailKey,
		&i.GifKey,
		&i.ShareMode,
		&i.UploadID,
		&i.UploadParts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ViewCount,
	)
	return i, err
}

const getShareVideo = `-- name: GetShareVideo :one
SELECT v.id, v.title, v.description, v.status, v.duration_ms,
       v.source_key, v.hls_key, v.thumbnail_key, v.gif_key, v.share_mode,
       u.name AS author_name, u.avatar_url AS author_avatar,
       v.created_at, COALESCE(v.view_count, 0)::integer AS view_count
FROM videos v
JOIN users u ON v.user_id = u.id
WHERE v.id = $1 AND v.deleted_at IS NULL AND v.share_mode != 'private'
`

type GetShareVideoRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Status       VideoStatus        `json:"status"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	SourceKey    pgtype.Text        `json:"source_key"`
	HlsKey       pgtype.Text        `json:"hls_key"`
	ThumbnailKey pgtype.Text        `json:"thumbnail_key"`
	GifKey       pgtype.Text        `json:"gif_key"`
	ShareMode    ShareMode          `json:"share_mode"`
	AuthorName   string             `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ViewCount    int32              `json:"view_count"`
}

func (q *Queries) GetShareVideo(ctx context.Context, id pgtype.UUID) (GetShareVideoRow, error) {
	row := q.db.QueryRow(ctx, getShareVideo, id)
	var i GetShareVideoRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DurationMs,
		&i.SourceKey,
		&i.HlsKey,
		&i.ThumbnailKey,
		&i.GifKey,
		&i.ShareMode,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.CreatedAt,
		&i.ViewCount,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, user_id, title, description, status, duration_ms, recording_source, source_key, hls_key, thumbnail_key, gif_key, share_mode, upload_id, upload_parts, created_at, updated_at, deleted_at, view_count FROM videos WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVideoByID(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DurationMs,
		&i.RecordingSource,
		&i.SourceKey,
		&i.HlsKey,
		&i.ThumbnailKey,
		&i.GifKey,
		&i.ShareMode,
		&i.UploadID,
		&i.UploadParts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ViewCount,
	)
	return i, err
}

const listVideosByUser = `-- name: ListVideosByUser :many
SELECT id, user_id, title, description, status, duration_ms, recording_source, source_key, hls_key, thumbnail_key, gif_key, share_mode, upload_id, upload_parts, created_at, updated_at, deleted_at, view_count FROM videos
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVideosByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListVideosByUser(ctx context.Context, arg ListVideosByUserParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DurationMs,
			&i.RecordingSource,
			&i.SourceKey,
			&i.HlsKey,
			&i.ThumbnailKey,
			&i.GifKey,
			&i.ShareMode,
			&i.UploadID,
			&i.UploadParts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoUpload = `-- name: SetVideoUpload :exec
UPDATE videos SET upload_id = $2, source_key = $3, updated_at = NOW()
WHERE id = $1
`

type SetVideoUploadParams struct {
	ID        pgtype.UUID `json:"id"`
	UploadID  pgtype.Text `json:"upload_id"`
	SourceKey pgtype.Text `json:"source_key"`
}

func (q *Queries) SetVideoUpload(ctx context.Context, arg SetVideoUploadParams) error {
	_, err := q.db.Exec(ctx, setVideoUpload, arg.ID, arg.UploadID, arg.SourceKey)
	return err
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE videos SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteVideo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVideo, id)
	return err
}

const updateVideo = `-- name: UpdateVideo :exec
UPDATE videos SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    share_mode = COALESCE($4, share_mode),
    updated_at = NOW()
WHERE id = $1
`

type UpdateVideoParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	ShareMode   ShareMode   `json:"share_mode"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) error {
	_, err := q.db.Exec(ctx, updateVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ShareMode,
	)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE videos SET
    status = $2,
    hls_key = $3,
    thumbnail_key = $4,
    gif_key = $5,
    duration_ms = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateVideoStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       VideoStatus `json:"status"`
	HlsKey       pgtype.Text `json:"hls_key"`
	ThumbnailKey pgtype.Text `json:"thumbnail_key"`
	GifKey       pgtype.Text `json:"gif_key"`
	DurationMs   pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.Exec(ctx, updateVideoStatus,
		arg.ID,
		arg.Status,
		arg.HlsKey,
		arg.ThumbnailKey,
		arg.GifKey,
		arg.DurationMs,
	)
	return err
}
